name: CI

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ self-hosted, macos-latest, ubuntu-24.04-arm, macos-15-intel ]

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set OS and ARCH variables
        run: |
          echo "OS=${{ runner.os == 'Linux' && 'linux' || 'mac' }}" >> $GITHUB_ENV
          echo "ARCH=${{ runner.arch == 'X64' && '64' || 'arm64' }}" >> $GITHUB_ENV
        shell: bash

      - name: Set up dependencies for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq cmake build-essential clang default-jdk libicu-dev icu-devtools

      - name: Set up dependencies for macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew upgrade cmake 
          brew install automake autoconf
          brew install icu4c ucon64

      - name: Display versions macOs
        if: runner.os == 'macOS'
        run: |
          gcc -v
          g++ -v
          cmake --version          
          eval $(brew --cellar)/ucon64/*/bin/ucon64 -v

      - name: Display versions Linux
        if: runner.os == 'Linux'
        run: |
          gcc -v
          g++ -v
          cmake --version          
          uconv -v

      - name: Set env variables for macOS x64
        if: runner.os == 'macOS' && runner.arch == 'X64'
        run: |
          echo "C_INCLUDE_PATH=/usr/local/include" >> $GITHUB_ENV
          echo "CPLUS_INCLUDE_PATH=/usr/local/include" >> $GITHUB_ENV
        shell: bash

      - name: Set env variables for macOS ARM64
        if: runner.os == 'macOS' && runner.arch == 'ARM64'
        run: |
          echo "C_INCLUDE_PATH=/opt/homebrew/include" >> $GITHUB_ENV
          echo "CPLUS_INCLUDE_PATH=/opt/homebrew/include" >> $GITHUB_ENV
        shell: bash

      - name: Build for macOS
        if: runner.os == 'macOS'
        run: |
          mkdir build
          cmake -S . -B build
          cmake --build build

      - name: Build on Linux
        if: runner.os == 'Linux'
        run: |
          mkdir build
          cmake -S . -B build
          cmake --build build

      - name: ls
        run: ls
        shell: bash

      - name: Copy wapiti linux artifacts
        if: runner.os == 'Linux'
        run: |
          mkdir -p output/libwapiti/${{ env.OS }}/${{ env.ARCH }}
          cp build/*.so output/libwapiti/${{ env.OS }}/${{ env.ARCH }}
          cp build/wapiti_runner output/libwapiti/${{ env.OS }}/${{ env.ARCH }}

      - name: Copy wapiti macos artifacts
        if: runner.os == 'macOS'
        run: |
          mkdir -p output/libwapiti/${{ env.OS }}/${{ env.ARCH }}
          cp build/*.dylib output/libwapiti/${{ env.OS }}/${{ env.ARCH }}
          cp build/wapiti_runner output/libwapiti/${{ env.OS }}/${{ env.ARCH }}

      - name: Save libraries
        uses: actions/upload-artifact@v4
        with:
          name: libwapiti-lib-${{ env.OS }}-${{ env.ARCH }}
          path: output

  assemble-artifact:
    needs: [ build ]
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: output
      - name: Move contents to output directory
        run: |
          for dir in output/*; do
            if [ -d "$dir" ]; then
              rsync -a "$dir"/* output/
              rm -rf "$dir"
            fi
          done
        shell: bash
      - name: Display structure of downloaded files
        run: ls -R
      - name: Get the revision ID
        id: extract_rev_id
        run: |
          SHORT_COMMIT_ID=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "short_commit_id=${SHORT_COMMIT_ID}" >> $GITHUB_OUTPUT
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libwapiti-bin-all-${{ steps.extract_rev_id.outputs.short_commit_id }}
          path: output